// Professional invoice PDF generator for TyreBook.
//
// Provides:
//   - buildGstInvoiceHtml(opts)   → full Indian GST Tax Invoice (A4)
//   - buildKachaBillHtml(opts)    → non-GST Cash Memo (A4)
//   - generateAndShareInvoice     → share/download (auto-chooses layout by opts.invoiceType or sale.invoiceKind)
//   - generateAndShareKachaBill   → convenience wrapper for kacha
//   - printInvoice / printKachaBill → native print dialog
//
// The PDFs are generated by expo-print from HTML/CSS — this works on iOS,
// Android and the web preview without any native module rebuild.

import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";

import type { Sale } from "@/src/constants/inventory";
import type { ShopSettings } from "@/src/firebase/master";
import { amountInWords } from "@/src/utils/amountInWords";

/* --------------------------------- helpers -------------------------------- */

function esc(v: string | number | undefined | null): string {
  if (v === null || v === undefined) return "";
  return String(v).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c] as string));
}

function inr(n: number): string {
  const safe = Number.isFinite(n) ? n : 0;
  return "₹" + safe.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function fmtDate(ts: number): string {
  return new Date(ts).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

/* Detect if the sale is inter-state by comparing state codes. */
function isInterstateSale(sale: Sale, shop: ShopSettings): boolean {
  if (typeof sale.isInterstate === "boolean") return sale.isInterstate;
  const shopState = (sale.shopStateCode || shop.stateCode || "").trim();
  const custState = (sale.customerStateCode || "").trim();
  if (!custState || !shopState) return false;
  return custState !== shopState;
}

/* Vehicle category id → readable label for the invoice line. */
const CATEGORY_LABEL: Record<string, string> = {
  bike: "Bike & Scooty",
  car: "Car",
  auto: "Auto Rickshaw",
  tractor: "Tractor",
  truck: "Truck",
  bus: "Bus",
  otr: "OTR / Earthmover",
};

/* ---------------------------------- types --------------------------------- */

export type InvoiceType =
  | "Tax Invoice"
  | "GST Invoice"
  | "Kacha Bill"
  | "Non-GST Invoice"
  | "Estimate"
  | "Quotation"
  | "Delivery Challan"
  | "Purchase Order";

export interface BuildInvoiceOptions {
  invoiceType: InvoiceType;
  invoiceNumber: string;
  sale: Sale;
  shop: ShopSettings;
  upiId?: string;
}

/* -------------------------- shared style tokens --------------------------- */

const SHARED_CSS = `
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif; color: #1B1F1E; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .page { padding: 24px 28px; max-width: 800px; margin: 0 auto; }
  .hdr { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #006B5F; padding-bottom: 14px; }
  .brand-block { display: flex; gap: 12px; align-items: flex-start; }
  .logo { width: 56px; height: 56px; border-radius: 8px; background: #006B5F; color: #FFFFFF; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 24px; }
  .logo img { width: 100%; height: 100%; object-fit: contain; border-radius: 8px; }
  .brand { font-size: 22px; font-weight: 800; color: #006B5F; margin: 0; line-height: 1.1; }
  .muted { color: #6F7978; font-size: 11px; margin-top: 2px; }
  .doc-type { text-align: right; }
  .doc-type h1 { margin: 0; font-size: 20px; color: #006B5F; letter-spacing: 0.5px; }
  .grid2 { display: flex; gap: 12px; margin-top: 14px; }
  .card { flex: 1; padding: 10px 12px; border: 1px solid #DDE5E4; border-radius: 8px; }
  .card h4 { margin: 0 0 6px; font-size: 10px; color: #006B5F; text-transform: uppercase; letter-spacing: 1px; font-weight: 700; }
  table.items { width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 12px; }
  table.items th { background: #CCE8E3; color: #05201C; text-align: left; padding: 8px; border: 1px solid #A8CFC8; font-weight: 700; font-size: 11px; }
  table.items td { padding: 8px; border: 1px solid #DDE5E4; vertical-align: top; }
  table.items td.num, table.items th.num { text-align: right; }
  table.items td.ctr, table.items th.ctr { text-align: center; }
  .totals { margin-top: 14px; display: flex; justify-content: space-between; gap: 20px; }
  .totals .left { flex: 1; font-size: 11px; }
  .totals .left b { color: #05201C; }
  .totals .right { min-width: 260px; font-size: 12px; }
  .totals .right .line { display: flex; justify-content: space-between; padding: 3px 0; }
  .totals .right .grand { border-top: 2px solid #006B5F; margin-top: 6px; padding-top: 6px; font-weight: 800; color: #006B5F; font-size: 14px; }
  .bank { margin-top: 14px; padding: 10px; border: 1px dashed #A8CFC8; border-radius: 8px; font-size: 11px; background: #F1F8F6; }
  .bank h4 { margin: 0 0 4px; color: #006B5F; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  .decl { margin-top: 14px; padding: 10px; border: 1px solid #DDE5E4; border-radius: 8px; font-size: 10px; color: #4A5453; }
  .sign { margin-top: 24px; display: flex; justify-content: space-between; align-items: flex-end; gap: 20px; font-size: 11px; }
  .sign .sig-block { text-align: center; min-width: 200px; }
  .sign .sig-line { border-top: 1px solid #1B1F1E; margin-top: 40px; padding-top: 4px; font-weight: 700; }
  .thanks { text-align: center; font-size: 12px; color: #006B5F; margin-top: 14px; font-weight: 700; }
`;

/* ----------------------------- GST Tax Invoice ---------------------------- */

export function buildGstInvoiceHtml(opts: BuildInvoiceOptions): string {
  const { sale, shop, invoiceNumber } = opts;
  const invoiceType = opts.invoiceType || "Tax Invoice";
  const qty = Number(sale.quantity) || 0;
  const rate = Number(sale.priceList) || Number(sale.sellingPrice) || 0;
  const discountPerUnit = Number(sale.discountAmount) || 0;
  const taxableUnit = Math.max(0, rate - discountPerUnit);
  const taxable = +(taxableUnit * qty).toFixed(2);
  const gstPct = Number(sale.gstPercent) || 0;
  const totalGst = +((taxable * gstPct) / 100).toFixed(2);
  const grandTotal = +(taxable + totalGst).toFixed(2);
  const interstate = isInterstateSale(sale, shop);
  const cgst = interstate ? 0 : +(totalGst / 2).toFixed(2);
  const sgst = interstate ? 0 : +(totalGst - cgst).toFixed(2);
  const igst = interstate ? totalGst : 0;
  const hsn = sale.hsnCode || shop.hsnCode || "4011";
  const categoryLabel = CATEGORY_LABEL[sale.categoryId] || sale.categoryId;
  const roundedTotal = Math.round(grandTotal);
  const rounding = +(roundedTotal - grandTotal).toFixed(2);
  const shopStateName = shop.stateName || "";
  const bankBlock =
    shop.bankName || shop.bankAccountNumber || shop.upiId
      ? `<div class="bank">
          <h4>Bank Details</h4>
          ${shop.bankName ? `<div><b>Bank:</b> ${esc(shop.bankName)}</div>` : ""}
          ${shop.bankAccountNumber ? `<div><b>A/C No:</b> ${esc(shop.bankAccountNumber)}</div>` : ""}
          ${shop.bankIFSC ? `<div><b>IFSC:</b> ${esc(shop.bankIFSC)}</div>` : ""}
          ${shop.bankBranch ? `<div><b>Branch:</b> ${esc(shop.bankBranch)}</div>` : ""}
          ${shop.upiId ? `<div><b>UPI:</b> ${esc(shop.upiId)}</div>` : ""}
        </div>`
      : "";
  const logoBlock = shop.logoUri
    ? `<div class="logo"><img src="${esc(shop.logoUri)}" alt="logo" /></div>`
    : `<div class="logo">${esc((shop.shopName || "TB").trim().charAt(0).toUpperCase() || "T")}</div>`;

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<title>${esc(invoiceType)} ${esc(invoiceNumber)}</title>
<style>@page { size: A4; margin: 10mm; } ${SHARED_CSS}</style>
</head>
<body>
  <div class="page">
    <div class="hdr">
      <div class="brand-block">
        ${logoBlock}
        <div>
          <div class="brand">${esc(shop.shopName || "TyreBook")}</div>
          <div class="muted">${esc(shop.address || "")}</div>
          <div class="muted">Ph: ${esc(shop.phone || "")}${shop.email ? " · " + esc(shop.email) : ""}</div>
          ${shop.gstin ? `<div class="muted"><b>GSTIN:</b> ${esc(shop.gstin)}${shopStateName ? " · State: " + esc(shopStateName) : ""}</div>` : ""}
          ${shop.panNumber ? `<div class="muted"><b>PAN:</b> ${esc(shop.panNumber)}</div>` : ""}
        </div>
      </div>
      <div class="doc-type">
        <h1>${esc(invoiceType.toUpperCase())}</h1>
        <div class="muted"><b>Invoice #:</b> ${esc(invoiceNumber)}</div>
        <div class="muted"><b>Date:</b> ${fmtDate(sale.date)}</div>
        <div class="muted"><b>Payment:</b> ${esc(sale.paymentMode)}</div>
      </div>
    </div>

    <div class="grid2">
      <div class="card">
        <h4>Bill To</h4>
        <div><b>${esc(sale.customerName || "Walk-in customer")}</b></div>
        ${sale.mobileNumber ? `<div class="muted">Mob: ${esc(sale.mobileNumber)}</div>` : ""}
        ${sale.customerAddress ? `<div class="muted">${esc(sale.customerAddress)}</div>` : ""}
        ${sale.customerGstin ? `<div class="muted"><b>GSTIN:</b> ${esc(sale.customerGstin)}</div>` : ""}
        ${sale.vehicleNumber ? `<div class="muted"><b>Vehicle:</b> ${esc(sale.vehicleNumber)}</div>` : ""}
      </div>
      <div class="card">
        <h4>Vehicle & Item</h4>
        <div><b>${esc(categoryLabel)}</b></div>
        <div class="muted">Class: ${esc(sale.tyreClass || "new").toUpperCase()}</div>
        <div class="muted">Interstate: ${interstate ? "Yes (IGST)" : "No (CGST + SGST)"}</div>
        <div class="muted">HSN Code: ${esc(hsn)}</div>
      </div>
    </div>

    <table class="items">
      <thead>
        <tr>
          <th class="ctr" style="width:26px">#</th>
          <th>Product Description</th>
          <th class="ctr" style="width:60px">HSN</th>
          <th class="ctr" style="width:36px">Qty</th>
          <th class="num" style="width:80px">Rate</th>
          <th class="num" style="width:70px">Discount</th>
          <th class="num" style="width:80px">Taxable</th>
          <th class="ctr" style="width:44px">GST%</th>
          <th class="num" style="width:80px">GST Amt</th>
          <th class="num" style="width:90px">Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="ctr">1</td>
          <td>
            <div><b>${esc(sale.brand)} ${esc(sale.model)}</b></div>
            <div class="muted">Size: ${esc(sale.size)}${sale.tyreClass && sale.tyreClass !== "new" ? " · " + esc(sale.tyreClass) : ""}</div>
          </td>
          <td class="ctr">${esc(hsn)}</td>
          <td class="ctr">${qty}</td>
          <td class="num">${inr(rate)}</td>
          <td class="num">${inr(+(discountPerUnit * qty).toFixed(2))}</td>
          <td class="num">${inr(taxable)}</td>
          <td class="ctr">${gstPct}%</td>
          <td class="num">${inr(totalGst)}</td>
          <td class="num"><b>${inr(+(taxable + totalGst).toFixed(2))}</b></td>
        </tr>
      </tbody>
    </table>

    <div class="totals">
      <div class="left">
        <div><b>Amount in Words:</b></div>
        <div>${esc(amountInWords(roundedTotal))}</div>
      </div>
      <div class="right">
        <div class="line"><span>Taxable Amount</span><span>${inr(taxable)}</span></div>
        ${
          interstate
            ? `<div class="line"><span>IGST (${gstPct}%)</span><span>${inr(igst)}</span></div>`
            : `<div class="line"><span>CGST (${(gstPct / 2).toFixed(2)}%)</span><span>${inr(cgst)}</span></div>
               <div class="line"><span>SGST (${(gstPct / 2).toFixed(2)}%)</span><span>${inr(sgst)}</span></div>`
        }
        <div class="line"><span>Total GST</span><span>${inr(totalGst)}</span></div>
        ${rounding !== 0 ? `<div class="line"><span>Round Off</span><span>${inr(rounding)}</span></div>` : ""}
        <div class="line grand"><span>Grand Total</span><span>${inr(roundedTotal)}</span></div>
      </div>
    </div>

    ${bankBlock}

    <div class="decl">
      <b>Declaration:</b> ${esc(shop.declaration || "We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.")}
    </div>

    <div class="sign">
      <div>
        <div class="muted">${esc(shop.invoiceFooter || "Thank you for your business!")}</div>
      </div>
      <div class="sig-block">
        <div class="sig-line">Authorised Signatory${shop.signatureName ? " · " + esc(shop.signatureName) : ""}</div>
        <div class="muted">For <b>${esc(shop.shopName || "TyreBook")}</b></div>
      </div>
    </div>
  </div>
</body></html>`;
}

/* -------------------------- Kacha Bill / Cash Memo ------------------------ */

export function buildKachaBillHtml(opts: BuildInvoiceOptions): string {
  const { sale, shop, invoiceNumber } = opts;
  const qty = Number(sale.quantity) || 0;
  const rate = Number(sale.sellingPrice) || 0;
  const total = +(qty * rate).toFixed(2);
  const rounded = Math.round(total);
  const logoBlock = shop.logoUri
    ? `<div class="logo"><img src="${esc(shop.logoUri)}" alt="logo" /></div>`
    : `<div class="logo">${esc((shop.shopName || "TB").trim().charAt(0).toUpperCase() || "T")}</div>`;

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<title>Cash Memo ${esc(invoiceNumber)}</title>
<style>@page { size: A4; margin: 10mm; } ${SHARED_CSS}</style>
</head>
<body>
  <div class="page">
    <div class="hdr">
      <div class="brand-block">
        ${logoBlock}
        <div>
          <div class="brand">${esc(shop.shopName || "TyreBook")}</div>
          <div class="muted">${esc(shop.address || "")}</div>
          <div class="muted">Ph: ${esc(shop.phone || "")}${shop.email ? " · " + esc(shop.email) : ""}</div>
        </div>
      </div>
      <div class="doc-type">
        <h1>CASH MEMO</h1>
        <div class="muted"><b>Bill #:</b> ${esc(invoiceNumber)}</div>
        <div class="muted"><b>Date:</b> ${fmtDate(sale.date)}</div>
        <div class="muted"><b>Payment:</b> ${esc(sale.paymentMode)}</div>
      </div>
    </div>

    <div class="grid2">
      <div class="card">
        <h4>Customer</h4>
        <div><b>${esc(sale.customerName || "Walk-in customer")}</b></div>
        ${sale.mobileNumber ? `<div class="muted">Mob: ${esc(sale.mobileNumber)}</div>` : ""}
        ${sale.vehicleNumber ? `<div class="muted"><b>Vehicle:</b> ${esc(sale.vehicleNumber)}</div>` : ""}
      </div>
      <div class="card">
        <h4>Vehicle Type</h4>
        <div><b>${esc(CATEGORY_LABEL[sale.categoryId] || sale.categoryId)}</b></div>
      </div>
    </div>

    <table class="items">
      <thead>
        <tr>
          <th class="ctr" style="width:26px">#</th>
          <th>Product Description</th>
          <th class="ctr" style="width:60px">Qty</th>
          <th class="num" style="width:100px">Rate</th>
          <th class="num" style="width:120px">Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="ctr">1</td>
          <td>
            <div><b>${esc(sale.brand)} ${esc(sale.model)}</b></div>
            <div class="muted">Size: ${esc(sale.size)}</div>
          </td>
          <td class="ctr">${qty}</td>
          <td class="num">${inr(rate)}</td>
          <td class="num"><b>${inr(total)}</b></td>
        </tr>
      </tbody>
    </table>

    <div class="totals">
      <div class="left">
        <div><b>Amount in Words:</b></div>
        <div>${esc(amountInWords(rounded))}</div>
        <div class="muted" style="margin-top:4px">This is a Cash Memo (no GST charged).</div>
      </div>
      <div class="right">
        <div class="line grand"><span>Total</span><span>${inr(rounded)}</span></div>
      </div>
    </div>

    <div class="sign">
      <div>
        <div class="muted">${esc(shop.invoiceFooter || "Thank you for your business!")}</div>
      </div>
      <div class="sig-block">
        <div class="sig-line">Authorised Signatory${shop.signatureName ? " · " + esc(shop.signatureName) : ""}</div>
        <div class="muted">For <b>${esc(shop.shopName || "TyreBook")}</b></div>
      </div>
    </div>
  </div>
</body></html>`;
}

/* --------------------------- unified entry points ------------------------- */

function pickBuilder(opts: BuildInvoiceOptions): (o: BuildInvoiceOptions) => string {
  const kind = opts.sale.invoiceKind || opts.invoiceType;
  if (kind === "Kacha Bill" || kind === "Non-GST Invoice" || opts.invoiceType === "Kacha Bill")
    return buildKachaBillHtml;
  return buildGstInvoiceHtml;
}

export function buildInvoiceHtml(opts: BuildInvoiceOptions): string {
  return pickBuilder(opts)(opts);
}

export async function generateAndShareInvoice(opts: BuildInvoiceOptions): Promise<string | null> {
  const html = pickBuilder(opts)(opts);
  try {
    const { uri } = await Print.printToFileAsync({ html, base64: false });
    if (Platform.OS === "web") {
      // Web: open in new tab so user can download / print.
      try {
        const w = window.open(uri, "_blank");
        if (!w) return uri;
      } catch {
        // fallthrough
      }
      return uri;
    }
    if (!(await Sharing.isAvailableAsync())) return uri;
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: `${opts.invoiceType} ${opts.invoiceNumber}`,
      UTI: "com.adobe.pdf",
    });
    return uri;
  } catch (e) {
    console.warn("[invoicePdf] generateAndShareInvoice failed", e);
    return null;
  }
}

export async function generateAndShareKachaBill(opts: BuildInvoiceOptions): Promise<string | null> {
  return generateAndShareInvoice({ ...opts, invoiceType: "Kacha Bill" });
}

export async function printInvoice(opts: BuildInvoiceOptions): Promise<void> {
  const html = pickBuilder(opts)(opts);
  try {
    await Print.printAsync({ html });
  } catch (e) {
    console.warn("[invoicePdf] printInvoice failed", e);
  }
}
